### ISSUE TITLE
scihubify will stop working with Firefox 57 (mid November)

### ISSUE THREAD

**Issue by mozfreddyb** [revcherrycoke/scihubify#5]
Hi!

Firefox is changing the way add-ons work and will deprecate all legacy add-ons by mid November.
[Here's a guide on how to port your add-on to the new API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_legacy_Firefox_add-on#SDK_Extensions)

**Comment by cossio** [comment]
@mozfreddyb Do you know how to do this? This repo looks dead.

**Comment by cossio** [comment]
@mozfreddyb  Any reason why you closed this? You found a solution?

**Comment by mozfreddyb** [comment]
No solution, just figured this is a dead repo anyway.

**Comment by cossio** [comment]
I think the issue should be left open, just in case someone else that knows how to fix it decides to take a look at it.

**Comment by meepiquitous** [comment]
Looks like there has been a port (Scihubify2) but the links on Mozilla and repo on Github are gone. :(
